version: '3.7'

services:
  golang_aula:
    image: golang:latest
    container_name: gouninassauu
    working_dir: /pratica
    volumes:
      - $HOME/workspace/aula:/pratica
    command: tail -f /dev/null
  
  mysql_db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_db
    ports:
      - "8080:80"
    depends_on:
      - mysql_db